# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

def myPods
  pod 'MobileCenter'
end

target 'Swfitnotes' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  myPods
  # Pods for Swfitnotes
end 

  target 'SwfitnotesTests' do
    inherit! :search_paths
    myPods
  end

  target 'SwfitnotesUITests' do
    inherit! :search_paths
    myPods
  end
